title: Thijs Smits
author: Thijs Smits
email: beyanora@gmail.com
description: >-
  This is the website of a programmer/\*\*/\* who lives in Maastricht.
baseurl: ""
url: "https://www.thijssmits.com"
github_username: tssmits
show_excerpts: true

markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
